### ISSUE TITLE
news:yc doesn't work anymore

### ISSUE THREAD

**Issue by sekrause** [grp/newsyc#130]
Probably due to some recent markup changes news:yc is not usable anymore. It now shows some raw HTML in the stories overview and loading comments stopped working.

**Comment by samuelclay** [comment]
I hope this app is still being worked on. It's my favorite HN client and only needs a few tweaks to get back to normal.

**Comment by Tyilo** [comment]
:+1:

**Comment by mattytrentini** [comment]
I love the app too...I'm not at all familiar with the codebase but if one of the regular contributors aren't able to investigate I'll have to dive in and take a look... :)

**Comment by guillaume-nargeot** [comment]
+1

**Comment by tyilo** [comment]
@sekrause was this fixed?

**Comment by sekrause** [comment]
I don't think so, it's just that the app seems dead, I don't use it anymore and didn't want to see this issue in my issue list anymore.
